### ISSUE TITLE
Release broken - main.js missing

### ISSUE THREAD

**Issue by ujikol** [kalvn/obsidian-export-to-html#1]
This is probaly the cause the pligin cannot be found in the community plugins. ???

**Comment by kalvn** [comment]
It's not yet validated by Obsidian's teams. Where did you install it from?

**Comment by ujikol** [comment]
I think I check from the releases in your github. I guess Obsidian want validate positively without that file. ?

**Comment by kalvn** [comment]
https://github.com/kalvn/obsidian-export-to-html/releases/tag/1.0.1

`main.js` is there as you can see.
